config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get '/signup' => 'users#new'
  post '/users' => 'users#create'

  get '/signin' => 'sessions#new'
  post '/signin' => 'sessions#create'
  get '/signout' => 'sessions#destroy'

  resources :questions do
    resources :answers
  end
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :question
  belongs_to :user
  validates :comment, :presence => true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers
  validates :query, :presence => true
end

app/models/user.rb
require 'bcrypt'

class User < ApplicationRecord
  attr_accessor :password
  validates_confirmation_of :password
  validates :username, :presence => true, :uniqueness => true
  before_save :encrypt_password
  has_many :questions

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(username, password)
    user = User.find_by "username = ?", username
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end

  def authorize
    if !current_user
      flash[:alert] = "you are not authorized to visit this page"
      redirect_to '/'
    end
  end


end

app/controllers/just_another_controller.rb
class JustAnotherController < ApplicationController
  before_action :authorize, only: [:secret]

  def secret
  end

end

app/controllers/questions_controller.rb
require 'pry'
class QuestionsController < ApplicationController

  def index
    @questions = Question.all
    render :index
  end

  def new
    @question = Question.new
    render :new
  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      flash[:notice] = " Question posted "
      redirect_to '/questions'
    else
      flash[:alert] = "There was a problem posting question"
      redirect_to new
    end
  end



  private

  def question_params
    params.require(:question).permit(:query)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @user = User.authenticate(params[:username], params[:password])
    if @user
      flash[:notice] = "You've signed in."
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing in. Please try again."
      redirect_to signin_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've signed out."
    redirect_to "/"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = " You've successfully signed up!"
      session[:user_id] = @user.id
      redirect_to "/"
    else
      flash[:alert] = "There was a problem signing up."
      redirect_to '/signup'
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password, :password_confirmation)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StackOverflow</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
    <%= current_user.username %> | <%= link_to "Sign out", '/signout' %>

    <% else %>
    <%= link_to "Sign up", 'signup' %> | <%= link_to "Sign in", '/signin' %>
    <% end %>
    <%= flash[:alert] %>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1>All Questions</h1>



<div class="container">
      <br/>
    <table>
      <tr>
        <th>Question</th>
        <th>Asked by</th>
      </tr>

	<% @questions.each do |question| %>

      <tr>
        <td> <%= link_to question.query, question_path(question) %></td>
        <td><%= question.user.username %></td>
      </tr>

  <% end %>
   </table>

   <br> <br> <br>

   <%= link_to "New Question", new_question_path %>


 </div>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= form_for @question do |f| %>
  <%= f.label :question %>
  <%= f.text_field :query %>
  <%= f.submit  %>
<% end %>

app/views/users/new.html.erb
<h1> Sign up</h1>
<%= form_for @user do |f| %>
  <%= f.label "Username" %>
  <%= f.text_field :username %>
  <%= f.label "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <%= f.submit "Sign Up" %>
<% end %>